# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7094bfcc620158279e7619c2f46731afdcf25ec051911916b83a0b43a82f0720c4e534a6de06d9712a4ebbb336fb3fe2fb3912665e1c9341a69713df154e16b7

test:
  secret_key_base: db4e50f1fad80906a2db7f403ded8c41aeaab5dc9ef3f73f542530072042634715bc09692b3b25220b14f36d2713fb0e597c18d57568a47489db94d1d42092b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
